<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Bitrix\Main\ORM\Query\Join;
use Models\AbstractIblockPropertyValuesTable;


class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {

        $map = [
                'PROCEDURE' => new ReferenceField(
                    'PROCEDURE',
                    ProcedurePropertyValuesTable::class,
                    ['=this.PROCEDURE_ID' => 'ref.IBLOCK_ELEMENT_ID'],
                    ['join_type'=>'inner']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub
    }
}
